### ISSUE TITLE
Add endpoint to list existing keyspaces

### ISSUE THREAD

**Issue by adutra** [k8ssandra/management-api-for-apache-cassandra#126]
In the k8ssandra-operator project we have a use case for a new endpoint in the Management API that would simply return a list of the existing keyspaces.

See https://github.com/k8ssandra/k8ssandra-operator/issues/106 for context.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-856) by [Unito](https://www.unito.io)
┆Epic: Stargate Controller Integration
┆Fix Versions: management-api-for-apache-cassandra-0.1.29
┆Issue Number: K8SSAND-856
┆Priority: Medium

**Comment by jdonenine** [comment]
I think a decent compromise here between creating a new endpoint and having to change the controller in https://github.com/k8ssandra/k8ssandra-operator/issues/106 would be to modify the API so that it can provide a parameter that allows for the behavior to be controlled.

So that the caller can explicitly say that they want the keyspace to be created only if doesn't exists or otherwise fail if it does exist.  We can leave the default to the current behavior so that we don't create a breaking change in the existing API.

What do you think about that @emerkle826 @adutra @adejanovski @jsanda ?

**Comment by emerkle826** [comment]
The current implementation of `createKeyspace` already does a create-if-not-exist (see [here](https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/master/management-api-agent-common/src/main/java/com/datastax/mgmtapi/NodeOpsProvider.java#L337)).
However, that implementation executes a query on the server. We could change the implementation and have Management API check to see if the keyspace already exists and simply return without executing the query, if that would be more efficient. This would not change the API contract, nor would it require K8ssandra operator to change what API it calls (if/when it starts calling createKeyspace for this purpose).

**Comment by emerkle826** [comment]
Fixed by #127
