### ISSUE TITLE
Filter metrics using the METRICS_FILTERS env variable

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/management-api-for-apache-cassandra#229]
The new metrics endpoint added in #228, should filter metrics based on the METRIC_FILTERS env variable that k8ssandra-operator generates:

```
METRIC_FILTERS:deny:org.apache.cassandra.metrics.Table deny:org.apache.cassandra.metrics.table allow:org.apache.cassandra.metrics.table.live_ss_table_count allow:org.apache.cassandra.metrics.Table.LiveSSTableCount allow:org.apache.cassandra.metrics.table.live_disk_space_used allow:org.apache.cassandra.metrics.table.LiveDiskSpaceUsed allow:org.apache.cassandra.metrics.Table.Pending allow:org.apache.cassandra.metrics.Table.Memtable allow:org.apache.cassandra.metrics.Table.Compaction allow:org.apache.cassandra.metrics.table.read allow:org.apache.cassandra.metrics.table.write allow:org.apache.cassandra.metrics.table.range allow:org.apache.cassandra.metrics.table.coordinator allow:org.apache.cassandra.metrics.table.dropped_mutations
```

The rules should apply as they did in MCAC and the filter names should be converted (basically replacing `.` with `_`) to match the names of the metrics generated by this new endpoint.

**Comment by burmanm** [comment]
Instead of removing the original, I'll add my plan (and implementation) as separate comment.

The design of metric filtering should support logic that allows filtering based on the tags as well as metric names. The original MCAC didn't understand any structure of the Cassandra metrics, it only pushed stuff as collectd names and that's it. And that's part of the reason why MCAC metrics don't work well in Prometheus for complex queries (or large amounts of data).

We can argue which way to write these metrics, but I opted to mimic the ``ServiceMonitor`` 's metricRelabing structure as it is familiar to Kubernetes devs. I've only implemented keep/drop as it does, but kept the semantics the same. That is, you could in theory copy existing Prometheus relabel rules for keep/drop and put them directly to the collector config. User does not need to learn anything new if they've used Prometheus previously.

The only difference could be a different Regexp engine in Java and Go. Order of the filters does not make any difference to processing. 

The configuration yaml ends up looking like (this is from my personal test, drops all metrics targeting a single table):

```yaml
filters:
  - source_labels: ["table"]
    separator: "@"
    regex: ".+"
    action: "drop"
```

The filtering has all the available labels, such as host (hostId), cluster, instance (pod_name), datacenter, rack, keyspace and table. In addition, I've also added (just like Prometheus) some internal ones for filtering that do not appear in the output: ``__name__`` for the metric name and ``__origname__`` to target the Cassandra's internal metric name. I do not recommend using the last one, but it's there if someone really wants to have weird outputs. 

The filtering itself happens on metric registration level, not at the query / update time, so it's a one time process.

**Comment by jsanda** [comment]
>We can argue which way to write these metrics, but I opted to mimic the `ServiceMonitor` 's metricRelabing structure as it is familiar to Kubernetes devs. I've only implemented keep/drop as it does, but kept the semantics the same. 

Are there any concerns about duplicating logic? Will it create additional maintenance overhead for example?

**Comment by burmanm** [comment]
> Are there any concerns about duplicating logic? Will it create additional maintenance overhead for example?

I'm not sure I understand the question. It's not strictly the same as Prometheus as it does the filtering on a different level, preventing reads from the Dropwizard completely, unlike with Prometheus which only filters when scraping the /metrics endpoint.

Any new feature is additional maintenance, but filtering was a requested feature.

**Comment by adejanovski** [comment]
> Any new feature is additional maintenance, but filtering was a requested feature.

Yes, I confirm. For performance reasons, we'll avoid extracting unnecessary metrics from the registry in the agent directly.

**Comment by adejanovski** [comment]
@burmanm, your plan looks good to me. Adhering to Prometheus standards will make it simpler for users to understand.
We can attach the filters using a mounted configmap and get rid of the env variable, that's fine by me.
The way this was implemented with mcac was hacky and not very flexible anyway.
