### ISSUE TITLE
5.0-beta1-ubi8 image start fail

### ISSUE THREAD

**Issue by xiongmozhou** [k8ssandra/management-api-for-apache-cassandra#537]
Starting Management API
mkdir: missing operand
Try 'mkdir --help' for more information.

[management-api-for-apache-cassandra](https://github.com/k8ssandra/management-api-for-apache-cassandra/tree/master)/[cassandra](https://github.com/k8ssandra/management-api-for-apache-cassandra/tree/master/cassandra)
/Dockerfile-5.0.ubi8 MCAC_PATH env is not found , why remove below
###
# Download and extract Metrics Collector
###
ENV MCAC_PATH=/opt/metrics-collector
RUN mkdir -m 775 ${MCAC_PATH} && \
    if test ! -e datastax-mcac-agent-${METRICS_COLLECTOR_VERSION}.tar.gz; then curl -L -O "https://github.com/datastax/metric-collector-for-apache-cassandra/releases/download/v${METRICS_COLLECTOR_VERSION}/datastax-mcac-agent-${METRICS_COLLECTOR_BUNDLE}.tar.gz"; fi && \
    tar --directory ${MCAC_PATH} --strip-components 1 --gzip --extract --file datastax-mcac-agent-${METRICS_COLLECTOR_BUNDLE}.tar.gz && \
    chmod -R g+w ${MCAC_PATH}

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/MAPI-65) by [Unito](https://www.unito.io)

**Comment by emerkle826** [comment]
@xiongmozhou Thanks for the issue. Management API images for Cassandra 5.0+ only work with the built-in metrics endpoint and no longer work with MCAC. That said, there are still some issues with Management API and Cassandra 5.0 since it was recently GA'ed. That issue should be tracked by #535 , though the issue currently doesn't detail why 5.0 doesn't start.

Currently, there are no plans to make images with Cassandra 5.0 and MCAC.

**Comment by xiongmozhou** [comment]
K8ssandraCluster add env is success
   
    containers:
      - name: cassandra
        env:
          - name: MGMT_API_DISABLE_MCAC
            value: "1"

**Comment by emerkle826** [comment]
Closing this as 5.0 does not work with MCAC and the new internal metrics endpoint should be used instead.
